FROM node:22-alpine AS build


WORKDIR /app


COPY package.json package-lock.json* ./


RUN npm install


COPY . .


ENV HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true


EXPOSE 5173


CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

